export const FETCH_USER_ACCOUNT = "FETCH_USER_ACCOUNT";
export const FETCH_USER_ACCOUNT_DETAIL = "FETCH_USER_ACCOUNT_DETAIL";
export const FETCH_USER_ACCOUNT_SUCCESS = "FETCH_USER_ACCOUNT_SUCCESS";
export const FETCH_USER_ACCOUNT_DETAIL_SUCCESS =
  "FETCH_USER_ACCOUNT_DETAIL_SUCCESS";
